name: Documentation

on:
  push:
    branches:
      - main
      - rel-*
    tags:
      - "v[0-9]+.[0-9]+"
  pull_request:
    branches:
      - main
      - rel-*

jobs:
  build:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Nix Environment
      uses: ./.github/actions/setup-nix
      with:
        tools: docs
        cache-id: common
    - run: postgrest-docs-build

  spellcheck:
    name: Run spellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Nix Environment
      uses: ./.github/actions/setup-nix
      with:
        tools: docs
        cache-id: common
    - run: postgrest-docs-spellcheck

  dictcheck:
    name: Run dictcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Nix Environment
        uses: ./.github/actions/setup-nix
        with:
          tools: docs
          cache-id: common
      - run: postgrest-docs-dictcheck

  linkcheck:
    name: Run linkcheck
    if: github.base_ref == 'main'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Nix Environment
      uses: ./.github/actions/setup-nix
      with:
        tools: docs
        cache-id: common
    - run: postgrest-docs-linkcheck
